apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onlineboutique-dev

resources:
- ../../../kustomize/base
- frontend-ingress.yaml

components:
- ../../../kustomize/components/non-public-frontend

images:
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/adservice
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/cartservice
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/checkoutservice
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/currencyservice
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/emailservice
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/frontend
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/loadgenerator
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/paymentservice
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/productcatalogservice
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/recommendationservice
  newTag: 2200b3747138
- name: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
  newName: us-central1-docker.pkg.dev/project-37ed24a7-5563-4ce5-a6f/microservices-demo/shippingservice
  newTag: 2200b3747138
