output "cluster_name" {
  description = "Target GKE cluster name where Argo CD was installed."
  value       = data.google_container_cluster.target.name
}

output "cluster_location" {
  description = "Target GKE cluster location where Argo CD was installed."
  value       = data.google_container_cluster.target.location
}

output "argocd_namespace" {
  description = "Namespace where Argo CD is deployed."
  value       = kubernetes_namespace.argocd.metadata[0].name
}

output "argocd_server_service_name" {
  description = "Kubernetes service name for Argo CD server endpoint."
  value       = "${var.argocd_release_name}-argocd-server"
}

output "argocd_admin_password_secret_name" {
  description = "Initial admin password secret generated by Argo CD chart."
  value       = "argocd-initial-admin-secret"
}

output "argocd_server_access_command" {
  description = "Command to check the Argo CD server service endpoint."
  value       = "kubectl -n ${var.argocd_namespace} get svc ${var.argocd_release_name}-argocd-server"
}

output "argocd_admin_password_command" {
  description = "Command to print Argo CD initial admin password."
  value       = "kubectl -n ${var.argocd_namespace} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d && echo"
}
