apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: online-boutique
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
    - .metadata.annotations["autopilot.gke.io/resource-adjustment"]
    - .metadata.annotations["autopilot.gke.io/warden-version"]
    - .spec.template.spec.containers[].resources
    - .spec.template.spec.initContainers[].resources
    - .spec.template.spec.securityContext.seccompProfile
    - .spec.template.spec.tolerations
  source:
    repoURL: https://github.com/Carshell/CodeX2026.git
    targetRevision: main
    path: deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: onlineboutique-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
