apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: online-boutique
  source:
    repoURL: https://github.com/Carshell/CodeX2026.git
    targetRevision: main
    path: deploy/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: onlineboutique-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
